apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::877716312368:role/Capstone-EKS-Server-EKSClusterFullAccessRole-RX47RKMRVFJO
      username: eksAccessrole
      groups:
        - system:masters        