apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - rolearn: arn:aws:iam::877716312368:user/udacity1
      username: udacity1
      groups:
        - system:masters        