apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: default
data:
  mapRoles: |
    - rolearn: arn:aws:iam::877716312368:role/EKS-Capstone-project
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - rolearn: arn:aws:iam::877716312368:user/udacity1
      username: udacity1
      groups:
        - system:bootstrappers
        - system:nodes
        - system:masters
