apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-eks
  labels:
    app: capstone-eks
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-eks
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%      
  template:
    metadata:
      labels:
        app: capstone-eks
    spec:
      containers:
      - name: capstone-eks
        image: vikrampanth/capstone-image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
